### ISSUE TITLE
Implementation of vocabulary checks

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/CdmInspection#1]
- [ ] For all custom mapped vocabularies extract the top 50 codes order by frequency from the source_to_concept map. The SME has to approve these top 50 codes. All custom mappings will be extracted as well as part of the package output. Note if the source_to_concept map is not used in the ETL process this information still has to be provided manually for the inspection.
- [x] For each domain generate statistics on the number of unmapped codes and and unmapped records.
- [x] Extract the vocabulary table and check if all the required vocabularies are present.
