### ISSUE TITLE
Implementation of other checks

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/CdmInspection#3]
- [x] Execution of short and longer running queries to test the performance of the system. This information is useful for the SME to provide further guidance on optimizing the infrastructure.
- [x] Checks on the number of CPUs, memory available in R.
- [x] Extract the versions of all installed R packages, checks if core HADES packages are installed.
- [x] Check if ATLAS is installed and WebAPI is running
- [x] Check if Achilles results are available in ATLAS.
- [x] Extraction of CDM_Source table
- [x] Schema Validation -> removed is in DQD
- [x] Count of concepts per vocabulary by standard, classification and non-standard.
- [x] Show top X=10 unmapped codes in each clinical domain
- [x] Read Data Density Report
- [x] Take counts from Achilles instead of CatalogExport
- [x] Concept counts round up to nearest 100 top 25 mapped codes per domain.
